### ISSUE TITLE
Write stdout to a log file

### ISSUE THREAD

**Issue by damien-list** [symfonycorp/croncape#1]
Hi,

It's not an issue, but I'm wondering if it's possible to write the standard output to a file without the -v parameter. I'd like to keep the email sent only when there is an error and log stdout to a file on each cron execution.

Really nice job by the way. 👍

**Comment by tucksaun** [comment]
It seems that using available unix tools should do the trick: `croncape bash -c "ls -lsa | tee /my/log/file"` ?

**Comment by damien-list** [comment]
Indeed, it does the trick! Thanks for the digging :)
