### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by jeromecx** [symfonycorp/croncape#9]
Hello  @fabpot,

When i'm trying to install Croncape following your documentation (https://github.com/symfonycorp/croncape#installation), like this : 
```bash
go get github.com/symfonycorp/croncape
```
I got this error : 
```txt
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

When i follow recommendations found here https://go.dev/doc/go-get-install-deprecation, like this :
```bash
go install github.com/symfonycorp/croncape@v1.3.0
```
Everything works as expected,

I guess the command is not the same, depending on the version of Go used localy. I'm using go version go1.18.1 linux/amd64

Thank you,

Jérôme

**Comment by fabpot** [comment]
Correct, fixed in 45a0157
